### ISSUE TITLE
[Feature Request] Make resource loader generic

### ISSUE THREAD

**Issue by Humberd** [utopia-rise/godot-kotlin-jvm#203]
Currently I need to manually cast the type like this:

```kotlin
val scene: PackedScene = ResourceLoader.load("res:/xxx.tscn") as PackedScene?
```

Would be cool to have it like this:

```kotlin
val scene: PackedScene = ResourceLoader.load("res:/xxx.tscn")

// or

val scene = ResourceLoader.load<PackedScene>("res:/xxx.tscn")
```

Currently C# has it in a generic way

**Comment by CedNaru** [comment]
https://github.com/utopia-rise/godot-kotlin-jvm/blob/ba18b41d68143701b371b355d584674402c1092c/kt/godot-library/src/main/kotlin/godot/global/GD.kt#L66

We already have it inside the GD singleton

**Comment by Humberd** [comment]
Oh, didn't know that. Wouldn't it be better for it to be available on the `ResourceLoader` object?

**Comment by CedNaru** [comment]
It's technically possible, but ResourceLoader is automatically generated from the api.json. We don't really want to write exceptions in the generation code to manually add content to them.
That's why it's in the GD Singleton that recreate all the top level functions inside GDScript. Load() is part of them.

**Comment by Humberd** [comment]
We can do a similar operation like with `getNodeAs`. We can add `As` suffix as an extension function.

**Comment by chippmann** [comment]
I find this a good idea. It would be consistent then.
