### ISSUE TITLE
Infer godot pulled version in CI from tag 

### ISSUE THREAD

**Issue by piiertho** [utopia-rise/godot-kotlin-jvm#229]
#228 currently remove inference of godot version in favor of hardcoded one.
This is necessary because godot version is inconsistent and we use `3.3.0` for `3.3` to keep it consistent.
The problem is there is no `3.3.0-stable` tag on godot's repo.
We need to find a way to keep consistency and pull the right version from repo.

**Comment by chippmann** [comment]
I'm just thinking: If your version suffix telling the supported godot version, shouldn't we then name our releases after the true godot releases. So in the case where this broke (godot `3.3`) shouldn't then be our version for such cases also `1.2.3-3.3` rather than `1.2.3-3.3.0`. Because if we are precise; there is no godot `3.3.0`.
