### ISSUE TITLE
OSX Editor hangs when shutting down JVM

### ISSUE THREAD

**Issue by xjchong** [utopia-rise/godot-kotlin-jvm#234]
## Current behaviour

Quitting the OSX editor causes this message to show forever:

<img width="542" alt="Screen Shot 2021-05-13 at 6 10 24 AM" src="https://user-images.githubusercontent.com/24628064/118111593-ebb4a580-b3b1-11eb-8a8b-70c0a79e8fe9.png">

There is no further message after `Shutting down the JVM...`

## Expected behaviour

There should be further messages after `Shutting down the JVM...`, eventually ending the running process.

## Possible steps to reproduce

1. Download the `godot-kotlin-jvm_editor_osx_.zip` asset from 0.2.0-3.3.0 tagged release.
2. Unzip, and there should be two files, `godot-bootstrap.jar` and `godot.osx.opt.tools.64`
3. Run the editor with `./godot.osx.opt.tools.64` (`chmod +x godot.osx.opt.tools.64` first if running not permitted)
4. The Godot project manager window should show. Open a project from here.
5. After the project opens, quit from the editor.
6. Shutting down message is logged, and hangs at that point. Any input in the terminal ends the process without any further messages:

<img width="393" alt="Screen Shot 2021-05-13 at 6 26 31 AM" src="https://user-images.githubusercontent.com/24628064/118113350-2b7c8c80-b3b4-11eb-905c-1e0301ea220c.png">

Additional notes:
- Java version is 14.0.1
<img width="483" alt="Screen Shot 2021-05-13 at 6 29 28 AM" src="https://user-images.githubusercontent.com/24628064/118113677-95953180-b3b4-11eb-9cca-233a84801e80.png">

**Comment by piiertho** [comment]
I confirm, I observe same on apple silicon.

**Comment by chippmann** [comment]
Another note: it only happens when the editor is launched through the project window. It does not happen when launching the editor directly from commandline using a project path and the `-e` option.

**Comment by chippmann** [comment]
Ok i tested this a bit and to me this is not a bug as the editor does not in fact hang.
The reason it looks like it would hang; when starting the editor without a project, the current process becomes the project selection screen. When you select a project, the process starts a new process (the editor) and after that one is started, the project selector is closed.
From there on the editor process is not in the foreground in the terminal. But prints still get published to said terminal because it got started from there basically the same if you would start a process with `nohup` or `$` at the end.

This also means you can safely close the terminal after the editor is started without the editor being stopped as it's not a child process of this terminal session anymore.

All of this can also be verified through the activitiy monitor. When it looks like it would "hang" all godot related processes (including jvm) are actually properly killed/finished.

That said; i also don't think we can do anything about how it looks in the terminal as this is normal behavior for backgrounded processes started from a terminal and we cannot alter how the project window launches the editor process without a change in godot itself (which is definitely not the scope of this repository).
